name: 🐛 Bug Report
description: Report a bug or issue with Air Boss
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below so we can fix it quickly.

  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you using?
      placeholder: "Example: iPhone 14 Pro, iPad Air, Samsung Galaxy S23"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Describe the bug you encountered
      placeholder: "Example: When I tap the schedule button, the app crashes and closes"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: What should have happened instead?
      placeholder: "Example: The schedule should open showing my flight list"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we make this happen again?
      placeholder: |
        1. Open the app
        2. Tap on 'Schedule' button
        3. App crashes
      value: |
        1.
        2.
        3.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of Air Boss are you using? (Find this in Settings → About)
      placeholder: "Example: 1.2.3"
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      options:
        - Every time
        - Sometimes
        - Just once
        - Not sure
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Any other details that might help? (Screenshots are great!)
      placeholder: You can paste screenshots directly here by dragging and dropping
    validations:
      required: false
