
name: 🐛 Bug Report
description: Report a bug or issue with Air Boss
title: "[BUG] "
labels: ["type: bug", "status: new"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please provide as much detail as possible.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) are affected?
      multiple: true
      options:
        - iOS Mobile App
        - Android Mobile App
        - Web Application
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using? (Check in app settings)
      placeholder: e.g., 2.2.6 (Build 147)
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste URLs

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Critical - App is unusable
        - High - Major feature broken
        - Medium - Feature partially broken
        - Low - Minor inconvenience
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...
