name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas for making Air Boss better.

  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: Is there something frustrating or missing in the current app?
      placeholder: "Example: It's hard to see all my scheduled flights for the month at once"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe your ideal solution or feature
      placeholder: "Example: A calendar view showing all upcoming flights with color-coding for different aircraft"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Critical - I can't use the app without this
        - High - Would make my life much easier
        - Medium - Would be nice to have
        - Low - Just an idea
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Any other ideas or workarounds?
      description: Are there other ways to solve this problem?
      placeholder: "Example: Or maybe a weekly summary email instead of a calendar view"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else we should know?
      placeholder: Screenshots from other apps, mockups, or any other helpful info
    validations:
      required: false
