name: ❓ Support Question
description: Ask for help or clarification
title: "[QUESTION] "
labels: ["type: question", "status: new"]
body:
  - type: markdown
    attributes:
      value: |
        Need help? We're here to assist! For general discussions, consider using [Discussions](https://github.com/bskyper/air-boss-support/discussions).

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform is your question about?
      multiple: true
      options:
        - iOS Mobile App
        - Android Mobile App
        - Web Application
        - General Question
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What is your question about?
      options:
        - Getting Started
        - Flight Logging
        - Aircraft Management
        - Reservations/Scheduling
        - Club Management
        - Billing/Invoices
        - User Account
        - Features/Functionality
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: What Have You Tried?
      description: What have you already attempted?
      placeholder: I tried...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any screenshots or additional information that might help
      placeholder: Screenshots, examples, etc.
